//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIM_ShuntCompensator
    {
        public int ModelID { get; set; }
        public int ID { get; set; }
        public string RDF_ID { get; set; }
        public string IdentifiedObject_name { get; set; }
        public Nullable<double> ShuntCompensator_yPerSection { get; set; }
        public Nullable<double> ShuntCompensator_voltSensitivity { get; set; }
        public Nullable<System.DateTime> ShuntCompensator_switchOnDate { get; set; }
        public Nullable<double> ShuntCompensator_switchOnCount { get; set; }
        public Nullable<double> ShuntCompensator_reactivePerSection { get; set; }
        public Nullable<double> ShuntCompensator_normalSections { get; set; }
        public Nullable<double> ShuntCompensator_nomU { get; set; }
        public Nullable<double> ShuntCompensator_nomQ { get; set; }
        public Nullable<double> ShuntCompensator_minU { get; set; }
        public Nullable<double> ShuntCompensator_maxU { get; set; }
        public Nullable<double> ShuntCompensator_maximumSections { get; set; }
        public Nullable<double> ShuntCompensator_impedance { get; set; }
        public Nullable<double> ShuntCompensator_aVRDelay { get; set; }
        public string ConductingEquipment_phases { get; set; }
        public string IdentifiedObject_exchangeName { get; set; }
        public string IdentifiedObject_pathName { get; set; }
        public string IdentifiedObject_mRID { get; set; }
        public string IdentifiedObject_localName { get; set; }
        public string IdentifiedObject_description { get; set; }
        public string IdentifiedObject_aliasName { get; set; }
        public string Equipment_MemberOf_EquipmentContainer { get; set; }
    }
}
