//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIM_ConformLoad
    {
        public int ModelID { get; set; }
        public int ID { get; set; }
        public string RDF_ID { get; set; }
        public string IdentifiedObject_name { get; set; }
        public Nullable<double> EnergyConsumer_qVexp { get; set; }
        public Nullable<double> EnergyConsumer_qfixedPct { get; set; }
        public Nullable<double> EnergyConsumer_qfixed { get; set; }
        public Nullable<double> EnergyConsumer_pVexp { get; set; }
        public Nullable<double> EnergyConsumer_pfixedPct { get; set; }
        public Nullable<double> EnergyConsumer_pfixed { get; set; }
        public Nullable<double> EnergyConsumer_pFexp { get; set; }
        public Nullable<double> EnergyConsumer_customerCount { get; set; }
        public Nullable<double> EnergyConsumer_criticalCustomerCount { get; set; }
        public string EnergyConsumer_connectionType { get; set; }
        public string ConductingEquipment_phases { get; set; }
        public string IdentifiedObject_exchangeName { get; set; }
        public string IdentifiedObject_pathName { get; set; }
        public string IdentifiedObject_mRID { get; set; }
        public string IdentifiedObject_localName { get; set; }
        public string IdentifiedObject_description { get; set; }
        public string IdentifiedObject_aliasName { get; set; }
        public string Equipment_MemberOf_EquipmentContainer { get; set; }
    }
}
