//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIM_TapChanger
    {
        public int ModelID { get; set; }
        public int ID { get; set; }
        public string RDF_ID { get; set; }
        public string IdentifiedObject_name { get; set; }
        public string TapChanger_tculControlMode { get; set; }
        public Nullable<double> TapChanger_subsequentDelay { get; set; }
        public Nullable<double> TapChanger_stepVoltageIncrement { get; set; }
        public Nullable<double> TapChanger_normalStep { get; set; }
        public Nullable<double> TapChanger_neutralStep { get; set; }
        public Nullable<double> TapChanger_lowStep { get; set; }
        public Nullable<double> TapChanger_initialDelay { get; set; }
        public Nullable<double> TapChanger_highStep { get; set; }
        public string IdentifiedObject_exchangeName { get; set; }
        public string IdentifiedObject_pathName { get; set; }
        public string IdentifiedObject_mRID { get; set; }
        public string IdentifiedObject_localName { get; set; }
        public string IdentifiedObject_description { get; set; }
        public string IdentifiedObject_aliasName { get; set; }
        public string TapChanger_TransformerWinding { get; set; }
        public string TapChanger_RegulationSchedule { get; set; }
        public string TapChanger_Terminal { get; set; }
    }
}
