//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIM_PowerTransformer
    {
        public int ModelID { get; set; }
        public int ID { get; set; }
        public string RDF_ID { get; set; }
        public string IdentifiedObject_name { get; set; }
        public string PowerTransformer_transformerType { get; set; }
        public string PowerTransformer_transfCoolingType { get; set; }
        public string PowerTransformer_phases { get; set; }
        public string PowerTransformer_magSatFlux { get; set; }
        public string PowerTransformer_magBaseU { get; set; }
        public string PowerTransformer_bmagSat { get; set; }
        public string IdentifiedObject_exchangeName { get; set; }
        public string IdentifiedObject_pathName { get; set; }
        public string IdentifiedObject_mRID { get; set; }
        public string IdentifiedObject_localName { get; set; }
        public string IdentifiedObject_description { get; set; }
        public string IdentifiedObject_aliasName { get; set; }
        public string Equipment_MemberOf_EquipmentContainer { get; set; }
        public string Terminal_1_ID { get; set; }
        public string Terminal_1_Name { get; set; }
        public string Terminal_2_ID { get; set; }
        public string Terminal_2_Name { get; set; }
        public string ConnectivityNode_A_ID { get; set; }
        public string ConnectivityNode_A_Name { get; set; }
        public string ConnectivityNode_B_ID { get; set; }
        public string ConnectivityNode_B_Name { get; set; }
        public string PowerTransformerEnd_A_ID { get; set; }
        public string PowerTransformerEnd_A_Name { get; set; }
        public string PowerTransformerEnd_B_ID { get; set; }
        public string PowerTransformerEnd_B_Name { get; set; }
        public Nullable<double> PowerTransformer_ratedS { get; set; }
        public Nullable<double> PowerTransformer_HighVoltage { get; set; }
        public Nullable<double> PowerTransformer_LowVoltage { get; set; }
        public string ParentName { get; set; }
    }
}
