//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;

    public partial class CIM_Model
    {
        //[Key]
        //[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public Nullable<System.DateTime> StartDT { get; set; }
        public Nullable<System.DateTime> EndDT { get; set; }
        public Nullable<System.DateTime> TerminateDT { get; set; }
        public string FileName { get; set; }
        public decimal? FileSize { get; set; }
        public int? CimVersion { get; set; }
        public long? ObjectCount { get; set; }
        public int? ModelCount { get; set; }
        public string Models { get; set; }
    }
}
