//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIM_PositionPoint
    {
        public int ModelID { get; set; }
        public int ID { get; set; }
        public string RDF_ID { get; set; }
        public string IdentifiedObject_name { get; set; }
        public string IdentifiedObject_exchangeName { get; set; }
        public string IdentifiedObject_pathName { get; set; }
        public string IdentifiedObject_mRID { get; set; }
        public string IdentifiedObject_localName { get; set; }
        public string IdentifiedObject_description { get; set; }
        public string IdentifiedObject_aliasName { get; set; }
        public string PositionPoint_Location { get; set; }
        public Nullable<double> PositionPoint_yPosition { get; set; }
        public Nullable<double> PositionPoint_xPosition { get; set; }
        public Nullable<int> PositionPoint_sequenceNumber { get; set; }
        public Nullable<double> PositionPoint_Latitude { get; set; }
        public Nullable<double> PositionPoint_Longitude { get; set; }
        public string PosistionPoint_Object_RDF_ID { get; set; }
        public Nullable<int> PositionPoint_ObjectType { get; set; }
    }
}
