//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIM_GeneratingUnit
    {
        public int ModelID { get; set; }
        public int ID { get; set; }
        public string RDF_ID { get; set; }
        public string IdentifiedObject_name { get; set; }
        public Nullable<double> GeneratingUnit_tieLinePF { get; set; }
        public Nullable<double> GeneratingUnit_stepChange { get; set; }
        public Nullable<double> GeneratingUnit_spinReserveRamp { get; set; }
        public Nullable<double> GeneratingUnit_shortPF { get; set; }
        public Nullable<double> GeneratingUnit_ratedNetMaxP { get; set; }
        public Nullable<double> GeneratingUnit_ratedGrossMaxP { get; set; }
        public Nullable<double> GeneratingUnit_penaltyFactor { get; set; }
        public string GeneratingUnit_genOperatingMode { get; set; }
        public Nullable<double> GeneratingUnit_normalPF { get; set; }
        public Nullable<double> GeneratingUnit_modelDetail { get; set; }
        public Nullable<double> GeneratingUnit_minOperatingP { get; set; }
        public Nullable<System.DateTime> GeneratingUnit_minimumOffTime { get; set; }
        public Nullable<double> GeneratingUnit_minEconomicP { get; set; }
        public string GeneratingUnit_maxOperatingP { get; set; }
        public Nullable<double> GeneratingUnit_maxEconomicP { get; set; }
        public Nullable<double> GeneratingUnit_maximumAllowableSpinngReserve { get; set; }
        public Nullable<double> GeneratingUnit_lowerRampRate { get; set; }
        public Nullable<double> GeneratingUnit_lowControlLimit { get; set; }
        public Nullable<double> GeneratingUnit_longPF { get; set; }
        public Nullable<double> GeneratingUnit_initialP { get; set; }
        public Nullable<double> GeneratingUnit_highControlLimit { get; set; }
        public Nullable<double> GeneratingUnit_governorSCD { get; set; }
        public Nullable<double> GeneratingUnit_governorMPL { get; set; }
        public Nullable<double> GeneratingUnit_genControlSource { get; set; }
        public Nullable<double> GeneratingUnit_genControlMode { get; set; }
        public Nullable<double> GeneratingUnit_fuelPriority { get; set; }
        public string GeneratingUnit_fastStartFlag { get; set; }
        public Nullable<double> GeneratingUnit_energyMinP { get; set; }
        public Nullable<double> GeneratingUnit_efficiency { get; set; }
        public string GeneratingUnit_dispReserveFlag { get; set; }
        public Nullable<double> GeneratingUnit_controlResponseRate { get; set; }
        public string GeneratingUnit_controlPulseLow { get; set; }
        public string GeneratingUnit_controlPulseHigh { get; set; }
        public Nullable<double> GeneratingUnit_controlDeadband { get; set; }
        public Nullable<double> GeneratingUnit_baseP { get; set; }
        public Nullable<double> GeneratingUnit_autoCntrlMarginP { get; set; }
        public Nullable<double> GeneratingUnit_allocSpinResP { get; set; }
        public string IdentifiedObject_exchangeName { get; set; }
        public string IdentifiedObject_pathName { get; set; }
        public string IdentifiedObject_mRID { get; set; }
        public string IdentifiedObject_localName { get; set; }
        public string IdentifiedObject_description { get; set; }
        public string IdentifiedObject_aliasName { get; set; }
        public string Equipment_MemberOf_EquipmentContainer { get; set; }
    }
}
