//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIM_VoltageLevel
    {
        public int ModelID { get; set; }
        public int ID { get; set; }
        public string RDF_ID { get; set; }
        public string IdentifiedObject_name { get; set; }
        public Nullable<double> VoltageLevel_lowVoltageLimit { get; set; }
        public Nullable<double> VoltageLevel_highVoltageLimit { get; set; }
        public string IdentifiedObject_exchangeName { get; set; }
        public string IdentifiedObject_pathName { get; set; }
        public string IdentifiedObject_mRID { get; set; }
        public string IdentifiedObject_localName { get; set; }
        public string IdentifiedObject_description { get; set; }
        public string IdentifiedObject_aliasName { get; set; }
        public string VoltageLevel_BaseVoltage { get; set; }
        public string VoltageLevel_MemberOf_Substation { get; set; }
    }
}
