//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIM_PowerTransformerEnd
    {
        public int ModelID { get; set; }
        public int ID { get; set; }
        public string RDF_ID { get; set; }
        public string IdentifiedObject_name { get; set; }
        public string IdentifiedObject_pathName { get; set; }
        public string IdentifiedObject_mRID { get; set; }
        public string IdentifiedObject_localName { get; set; }
        public string IdentifiedObject_description { get; set; }
        public string IdentifiedObject_aliasName { get; set; }
        public string PowerTransformerEnd_PowerTransformer { get; set; }
        public Nullable<double> PowerTransformerEnd_x { get; set; }
        public Nullable<double> PowerTransformerEnd_ratedU { get; set; }
        public string TransformerEnd_BaseVoltage { get; set; }
        public Nullable<double> BaseVoltage_nominalVoltage { get; set; }
        public Nullable<double> PowerTransformerEnd_b { get; set; }
        public Nullable<double> PowerTransformerEnd_r { get; set; }
        public string TransformerEnd_Terminal { get; set; }
        public Nullable<double> PowerTransformerEnd_ratedS { get; set; }
        public Nullable<int> TransformerEnd_endNumber { get; set; }
    }
}
