//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIM_EnergyConsumer
    {
        public int ModelID { get; set; }
        public int ID { get; set; }
        public string RDF_ID { get; set; }
        public Nullable<int> EnergyConsumer_customerCount { get; set; }
        public Nullable<double> EnergyConsumer_pfixed { get; set; }
        public Nullable<double> EnergyConsumer_pfixedPct { get; set; }
        public Nullable<double> EnergyConsumer_qfixed { get; set; }
        public Nullable<double> EnergyConsumer_qfixedPct { get; set; }
        public string ConductingEquipment_phases { get; set; }
        public string Equipment_normallyInService { get; set; }
        public string IdentifiedObject_name { get; set; }
        public string IdentifiedObject_pathName { get; set; }
        public string IdentifiedObject_mRID { get; set; }
        public string IdentifiedObject_localName { get; set; }
        public string IdentifiedObject_description { get; set; }
        public string IdentifiedObject_aliasName { get; set; }
        public string Equipment_EquipmentContainer { get; set; }
        public Nullable<int> ConnectivityNode_ID { get; set; }
        public string ConnectivityNode_Name { get; set; }
        public Nullable<int> PowerTransformer_ID { get; set; }
        public string ParentName { get; set; }
    }
}
