//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIM_PositionPointFormat
    {
        public int ID { get; set; }
        public string SourceFormatName { get; set; }
        public string SourceFormatID { get; set; }
        public string TargetName { get; set; }
        public string TargetID { get; set; }
    }
}
