//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIM_Command
    {
        public int ModelID { get; set; }
        public int ID { get; set; }
        public string RDF_ID { get; set; }
        public string IdentifiedObject_name { get; set; }
        public Nullable<double> Command_value { get; set; }
        public Nullable<double> Command_normalValue { get; set; }
        public Nullable<System.DateTime> Control_timeStamp { get; set; }
        public string Control_operationInProgress { get; set; }
        public string IdentifiedObject_exchangeName { get; set; }
        public string IdentifiedObject_pathName { get; set; }
        public string IdentifiedObject_mRID { get; set; }
        public string IdentifiedObject_localName { get; set; }
        public string IdentifiedObject_description { get; set; }
        public string IdentifiedObject_aliasName { get; set; }
        public string Command_MeasuredBy_Measurement { get; set; }
    }
}
