//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIM_TransformerWinding
    {
        public int ModelID { get; set; }
        public int ID { get; set; }
        public string RDF_ID { get; set; }
        public string IdentifiedObject_name { get; set; }
        public string TransformerWinding_xground { get; set; }
        public Nullable<double> TransformerWinding_x0 { get; set; }
        public Nullable<double> TransformerWinding_x { get; set; }
        public string TransformerWinding_windingType { get; set; }
        public Nullable<double> TransformerWinding_shortTermS { get; set; }
        public Nullable<double> TransformerWinding_rground { get; set; }
        public Nullable<double> TransformerWinding_ratedU { get; set; }
        public Nullable<double> TransformerWinding_ratedS { get; set; }
        public Nullable<double> TransformerWinding_r0 { get; set; }
        public Nullable<double> TransformerWinding_r { get; set; }
        public string TransformerWinding_insulationU { get; set; }
        public string TransformerWinding_grounded { get; set; }
        public Nullable<double> TransformerWinding_g0 { get; set; }
        public Nullable<double> TransformerWinding_g { get; set; }
        public Nullable<double> TransformerWinding_emergencyS { get; set; }
        public string TransformerWinding_connectionType { get; set; }
        public Nullable<double> TransformerWinding_b0 { get; set; }
        public Nullable<double> TransformerWinding_b { get; set; }
        public string ConductingEquipment_phases { get; set; }
        public string IdentifiedObject_exchangeName { get; set; }
        public string IdentifiedObject_pathName { get; set; }
        public string IdentifiedObject_mRID { get; set; }
        public string IdentifiedObject_localName { get; set; }
        public string IdentifiedObject_description { get; set; }
        public string IdentifiedObject_aliasName { get; set; }
        public string TransformerWinding_MemberOf_PowerTransformer { get; set; }
        public string ConductingEquipment_BaseVoltage { get; set; }
    }
}
