//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIM_ACLineSegment
    {
        public int ModelID { get; set; }
        public int ID { get; set; }
        public string RDF_ID { get; set; }
        public string IdentifiedObject_name { get; set; }
        public Nullable<double> Conductor_x0 { get; set; }
        public Nullable<double> Conductor_x { get; set; }
        public Nullable<double> Conductor_r0 { get; set; }
        public Nullable<double> Conductor_r { get; set; }
        public Nullable<double> Conductor_length { get; set; }
        public Nullable<double> Conductor_gch { get; set; }
        public Nullable<double> Conductor_g0ch { get; set; }
        public Nullable<double> Conductor_bch { get; set; }
        public Nullable<double> Conductor_b0ch { get; set; }
        public string ConductingEquipment_phases { get; set; }
        public string IdentifiedObject_exchangeName { get; set; }
        public string IdentifiedObject_pathName { get; set; }
        public string IdentifiedObject_mRID { get; set; }
        public string IdentifiedObject_localName { get; set; }
        public string IdentifiedObject_description { get; set; }
        public string IdentifiedObject_aliasName { get; set; }
        public string Equipment_MemberOf_EquipmentContainer { get; set; }
        public string ConductingEquipment_BaseVoltage { get; set; }
        public string Terminal_1_ID { get; set; }
        public string Terminal_1_Name { get; set; }
        public string Terminal_2_ID { get; set; }
        public string Terminal_2_Name { get; set; }
        public string ConnectivityNode_A_ID { get; set; }
        public string ConnectivityNode_A_Name { get; set; }
        public string ConnectivityNode_B_ID { get; set; }
        public string ConnectivityNode_B_Name { get; set; }
        public string ParentName { get; set; }
    }
}
