//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIM_SynchronousMachine
    {
        public int ModelID { get; set; }
        public int ID { get; set; }
        public string RDF_ID { get; set; }
        public string IdentifiedObject_name { get; set; }
        public Nullable<double> SynchronousMachine_xQuadTrans { get; set; }
        public Nullable<double> SynchronousMachine_xQuadSync { get; set; }
        public Nullable<double> SynchronousMachine_xQuadSubtrans { get; set; }
        public Nullable<double> SynchronousMachine_xDirectSync { get; set; }
        public Nullable<double> SynchronousMachine_xDirectSubtrans { get; set; }
        public Nullable<double> SynchronousMachine_x0 { get; set; }
        public Nullable<double> SynchronousMachine_x { get; set; }
        public string SynchronousMachine_type { get; set; }
        public Nullable<double> SynchronousMachine_referencePriority { get; set; }
        public Nullable<double> SynchronousMachine_ratedS { get; set; }
        public Nullable<double> SynchronousMachine_r0 { get; set; }
        public Nullable<double> SynchronousMachine_r { get; set; }
        public string SynchronousMachine_operatingMode { get; set; }
        public Nullable<double> SynchronousMachine_minU { get; set; }
        public Nullable<double> SynchronousMachine_minQ { get; set; }
        public Nullable<double> SynchronousMachine_maxU { get; set; }
        public Nullable<double> SynchronousMachine_maxQ { get; set; }
        public Nullable<double> SynchronousMachine_manualToAVR { get; set; }
        public Nullable<double> SynchronousMachine_inertia { get; set; }
        public Nullable<double> SynchronousMachine_damping { get; set; }
        public string SynchronousMachine_coolantType { get; set; }
        public string SynchronousMachine_coolantCondition { get; set; }
        public string SynchronousMachine_condenserP { get; set; }
        public string SynchronousMachine_baseQ { get; set; }
        public string SynchronousMachine_aVRToManualLead { get; set; }
        public string SynchronousMachine_aVRToManualLag { get; set; }
        public string ConductingEquipment_phases { get; set; }
        public string IdentifiedObject_exchangeName { get; set; }
        public string IdentifiedObject_pathName { get; set; }
        public string IdentifiedObject_mRID { get; set; }
        public string IdentifiedObject_localName { get; set; }
        public string IdentifiedObject_description { get; set; }
        public string IdentifiedObject_aliasName { get; set; }
        public string RegulatingCondEq_RegulationSchedule { get; set; }
        public string SynchronousMachine_MemberOf_GeneratingUnit { get; set; }
        public string Equipment_MemberOf_EquipmentContainer { get; set; }
    }
}
