//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class DGM_NodeBranch
    {
        public int CaseID { get; set; }
        public int NodeID { get; set; }
        public int BranchID { get; set; }
        public string BranchSide { get; set; }
        public Nullable<int> FeederHeadBusbarID { get; set; }
    }
}
