//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class DGM_LineElectricalParameter
    {
        public int ID { get; set; }
        public int LineID { get; set; }
        public Nullable<decimal> raa { get; set; }
        public Nullable<decimal> rab { get; set; }
        public Nullable<decimal> rac { get; set; }
        public Nullable<decimal> rbb { get; set; }
        public Nullable<decimal> rbc { get; set; }
        public Nullable<decimal> rcc { get; set; }
        public Nullable<decimal> xaa { get; set; }
        public Nullable<decimal> xab { get; set; }
        public Nullable<decimal> xac { get; set; }
        public Nullable<decimal> xbb { get; set; }
        public Nullable<decimal> xbc { get; set; }
        public Nullable<decimal> xcc { get; set; }
        public Nullable<decimal> Baa { get; set; }
        public Nullable<decimal> Bab { get; set; }
        public Nullable<decimal> Bac { get; set; }
        public Nullable<decimal> Bbb { get; set; }
        public Nullable<decimal> Bbc { get; set; }
        public Nullable<decimal> Bcc { get; set; }
    }
}
