//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class DGM_TraceBranch
    {
        public int IndexID { get; set; }
        public int ID { get; set; }
        public int CaseID { get; set; }
        public string Name { get; set; }
        public string EquipmentType { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public Nullable<int> ANodeID { get; set; }
        public Nullable<int> BNodeID { get; set; }
        public string Phase { get; set; }
        public Nullable<int> FeederHeadBusbarID { get; set; }
    }
}
