//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class DGM_TraceNode
    {
        public int CaseID { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> NoBranches { get; set; }
        public Nullable<int> NodeTypeID { get; set; }
        public Nullable<int> FeederHeadID { get; set; }
        public Nullable<int> FeederHeadBusbarID { get; set; }
    }
}
