//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class DGM_Switch
    {
        public int CaseID { get; set; }
        public int ID { get; set; }
        public Nullable<int> TraceID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ANodeID { get; set; }
        public Nullable<int> BNodeID { get; set; }
        public Nullable<int> Phase { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<bool> IsGangedOperated { get; set; }
        public Nullable<byte> NormalStatus { get; set; }
        public Nullable<decimal> NormalRatingAmp { get; set; }
        public Nullable<decimal> ShortCircuitRatingAmp { get; set; }
        public Nullable<int> NodeAFeederHeadID { get; set; }
        public Nullable<int> NodeBFeederHeadID { get; set; }
    }
}
