//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class DGM_BaseLine
    {
        public int IndexID { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> SwitchID { get; set; }
        public string ANodeName { get; set; }
        public string BNodeName { get; set; }
        public Nullable<decimal> LongTermRating { get; set; }
        public Nullable<decimal> ShortTermRating { get; set; }
        public Nullable<int> PhaseTypeID { get; set; }
        public Nullable<System.DateTime> StartDT { get; set; }
        public Nullable<System.DateTime> EndDT { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public Nullable<System.DateTime> TerminateDT { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<int> TerminateUserID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> LineType { get; set; }
        public Nullable<decimal> ImpedanceLength { get; set; }
        public string ConductorPhA { get; set; }
        public string ConductorPhB { get; set; }
        public string ConductorPhC { get; set; }
        public string ConductorNeutral { get; set; }
        public Nullable<int> NumberOfNeutrals { get; set; }
        public Nullable<int> UGType { get; set; }
        public Nullable<int> PhaseSequence { get; set; }
        public Nullable<int> SpaceID { get; set; }
        public Nullable<int> BaseFeederHeadID { get; set; }
        public Nullable<int> FeederHeadBusbarID { get; set; }
    }
}
