//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class DGM_BaseServicePoint
    {
        public int IndexID { get; set; }
        public long ID { get; set; }
        public string Name { get; set; }
        public string MeterNumber { get; set; }
        public Nullable<int> TransformerID { get; set; }
        public string ConnectivityNodeName { get; set; }
        public Nullable<int> VoltageRegulatorID { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> UpdateDT { get; set; }
        public Nullable<byte> NoPhases { get; set; }
        public Nullable<int> PhaseTypeID { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public Nullable<System.DateTime> TerminateDT { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<int> TerminateUserID { get; set; }
    }
}
