//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class DGM_Node
    {
        public int TraceID { get; set; }
        public int CaseID { get; set; }
        public int NodeID { get; set; }
        public Nullable<int> FeederHeadID { get; set; }
        public Nullable<int> SupplyBranchID { get; set; }
        public Nullable<byte> PhaseA { get; set; }
        public Nullable<byte> PhaseB { get; set; }
        public Nullable<byte> PhaseC { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsLoopNode { get; set; }
    }
}
