//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class DGM_BaseTransformer
    {
        public int IndexID { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> BaseFeederHeadID { get; set; }
        public string PrimaryNodeName { get; set; }
        public string SecondaryNodeName { get; set; }
        public Nullable<int> LineID { get; set; }
        public Nullable<int> XFTypeID { get; set; }
        public Nullable<int> XFConnectionTypeID { get; set; }
        public Nullable<int> PrimaryPhaseTypeID { get; set; }
        public Nullable<int> SecondaryPhaseTypeID { get; set; }
        public Nullable<decimal> RatingKVA { get; set; }
        public Nullable<decimal> RatingKVA_A { get; set; }
        public Nullable<decimal> RatingKVA_B { get; set; }
        public Nullable<decimal> RatingKVA_C { get; set; }
        public Nullable<bool> IsDER { get; set; }
        public Nullable<decimal> VLowLimit { get; set; }
        public Nullable<decimal> VHighLimit { get; set; }
        public Nullable<decimal> MaxLoading { get; set; }
        public string Description { get; set; }
        public Nullable<int> MaxViolationNu { get; set; }
        public Nullable<System.DateTime> StartDT { get; set; }
        public Nullable<System.DateTime> EndDT { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public Nullable<System.DateTime> TerminateDT { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<int> TerminateUserID { get; set; }
        public Nullable<int> SynchronizationStatusID { get; set; }
        public Nullable<decimal> VoltNomHigh { get; set; }
        public Nullable<decimal> VoltNomLow { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> FeederHeadBusbarID { get; set; }
    }
}
