//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class DGM_TraceFeederHead
    {
        public int CaseID { get; set; }
        public int ID { get; set; }
        public Nullable<int> SubstationID { get; set; }
        public string Name { get; set; }
        public Nullable<int> NodeID { get; set; }
        public Nullable<int> SwitchID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<decimal> KW_V_Factor { get; set; }
        public Nullable<decimal> MaxNeutralAmp { get; set; }
        public Nullable<decimal> MaxAmp { get; set; }
    }
}
