//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class DGM_ModelCase
    {
        public int ID { get; set; }
        public Nullable<int> UDCID { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public Nullable<byte> IsCIM { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public Nullable<System.DateTime> StartDT { get; set; }
        public Nullable<System.DateTime> StopDT { get; set; }
    }
}
