//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class DGM_FeederHead
    {
        public int TraceID { get; set; }
        public int CaseID { get; set; }
        public int FeederHeadID { get; set; }
        public Nullable<int> BackfeedFeederHeadID { get; set; }
        public Nullable<decimal> LoadFlowAMP { get; set; }
        public Nullable<decimal> LoadFlowAMP_Neutral { get; set; }
        public Nullable<decimal> LoadFlowKW_A { get; set; }
        public Nullable<decimal> LoadFlowKW_B { get; set; }
        public Nullable<decimal> LoadFlowKW_C { get; set; }
        public Nullable<decimal> LoadFlowKVAR_A { get; set; }
        public Nullable<decimal> LoadFlowKVAR_B { get; set; }
        public Nullable<decimal> LoadFlowKVAR_C { get; set; }
        public Nullable<decimal> LoadFlowDRKW_A { get; set; }
        public Nullable<decimal> LoadFlowDRKW_B { get; set; }
        public Nullable<decimal> LoadFlowDRKW_C { get; set; }
        public Nullable<int> FeederHeadBusbarID { get; set; }
    }
}
