//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;

    public partial class cim_import_dbEntities : DbContext
    {
        public cim_import_dbEntities() : base("name=EntityDataModel")
        {
        }

        public virtual DbSet<CIM_ACLineSegment> CIM_ACLineSegment { get; set; }
        public virtual DbSet<CIM_Analog> CIM_Analog { get; set; }
        public virtual DbSet<CIM_AnalogValue> CIM_AnalogValue { get; set; }
        public virtual DbSet<CIM_ApparentPowerLimit> CIM_ApparentPowerLimit { get; set; }
        public virtual DbSet<CIM_BaseVoltage> CIM_BaseVoltage { get; set; }
        public virtual DbSet<CIM_Breaker> CIM_Breaker { get; set; }
        public virtual DbSet<CIM_BusbarSection> CIM_BusbarSection { get; set; }
        public virtual DbSet<CIM_Command> CIM_Command { get; set; }
        public virtual DbSet<CIM_ConformLoad> CIM_ConformLoad { get; set; }
        public virtual DbSet<CIM_ConnectivityNode> CIM_ConnectivityNode { get; set; }
        public virtual DbSet<CIM_CurrentLimit> CIM_CurrentLimit { get; set; }
        public virtual DbSet<CIM_Disconnector> CIM_Disconnector { get; set; }
        public virtual DbSet<CIM_Discrete> CIM_Discrete { get; set; }
        public virtual DbSet<CIM_DiscreteValue> CIM_DiscreteValue { get; set; }
        public virtual DbSet<CIM_EnergyConsumer> CIM_EnergyConsumer { get; set; }
        public virtual DbSet<CIM_Feeder> CIM_Feeder { get; set; }
        public virtual DbSet<CIM_Fuse> CIM_Fuse { get; set; }
        public virtual DbSet<CIM_GeneratingUnit> CIM_GeneratingUnit { get; set; }
        public virtual DbSet<CIM_Ground> CIM_Ground { get; set; }
        public virtual DbSet<CIM_GroundDisconnector> CIM_GroundDisconnector { get; set; }
        public virtual DbSet<CIM_Line> CIM_Line { get; set; }
        public virtual DbSet<CIM_LoadBreakSwitch> CIM_LoadBreakSwitch { get; set; }
        public virtual DbSet<CIM_Location> CIM_Location { get; set; }
        public virtual DbSet<CIM_Model> CIM_Model { get; set; }
        public virtual DbSet<CIM_PositionPoint> CIM_PositionPoint { get; set; }
        public virtual DbSet<CIM_PositionPointFormat> CIM_PositionPointFormat { get; set; }
        public virtual DbSet<CIM_PowerTransformer> CIM_PowerTransformer { get; set; }
        public virtual DbSet<CIM_PowerTransformerEnd> CIM_PowerTransformerEnd { get; set; }
        public virtual DbSet<CIM_SetPoint> CIM_SetPoint { get; set; }
        public virtual DbSet<CIM_ShuntCompensator> CIM_ShuntCompensator { get; set; }
        public virtual DbSet<CIM_Substation> CIM_Substation { get; set; }
        public virtual DbSet<CIM_Switch> CIM_Switch { get; set; }
        public virtual DbSet<CIM_SynchronousMachine> CIM_SynchronousMachine { get; set; }
        public virtual DbSet<CIM_TapChanger> CIM_TapChanger { get; set; }
        public virtual DbSet<CIM_Terminal> CIM_Terminal { get; set; }
        public virtual DbSet<CIM_TransformerWinding> CIM_TransformerWinding { get; set; }
        public virtual DbSet<CIM_VoltageLevel> CIM_VoltageLevel { get; set; }


        /*
         One or more validation errors were detected during model generation:

CIMImport.DGM_BaseBusbarSection: : EntityType 'DGM_BaseBusbarSection' has no key defined. Define the key for this EntityType.
CIMImport.DGM_BaseTerminalToConnectivityNode: : EntityType 'DGM_BaseTerminalToConnectivityNode' has no key defined. Define the key for this EntityType.
CIMImport.DGM_Branch: : EntityType 'DGM_Branch' has no key defined. Define the key for this EntityType.
CIMImport.DGM_FeederHead: : EntityType 'DGM_FeederHead' has no key defined. Define the key for this EntityType.
CIMImport.DGM_Node: : EntityType 'DGM_Node' has no key defined. Define the key for this EntityType.
CIMImport.DGM_NodeBranch: : EntityType 'DGM_NodeBranch' has no key defined. Define the key for this EntityType.
CIMImport.DGM_Transformer: : EntityType 'DGM_Transformer' has no key defined. Define the key for this EntityType.
DGM_BaseBusbarSection: EntityType: EntitySet 'DGM_BaseBusbarSection' is based on type 'DGM_BaseBusbarSection' that has no keys defined.
DGM_BaseTerminalToConnectivityNode: EntityType: EntitySet 'DGM_BaseTerminalToConnectivityNode' is based on type 'DGM_BaseTerminalToConnectivityNode' that has no keys defined.
DGM_Branch: EntityType: EntitySet 'DGM_Branch' is based on type 'DGM_Branch' that has no keys defined.
DGM_FeederHead: EntityType: EntitySet 'DGM_FeederHead' is based on type 'DGM_FeederHead' that has no keys defined.
DGM_Node: EntityType: EntitySet 'DGM_Node' is based on type 'DGM_Node' that has no keys defined.
DGM_NodeBranch: EntityType: EntitySet 'DGM_NodeBranch' is based on type 'DGM_NodeBranch' that has no keys defined.
DGM_Transformer: EntityType: EntitySet 'DGM_Transformer' is based on type 'DGM_Transformer' that has no keys defined.
        */

        public virtual DbSet<DGM_BaseConnectivityNode> DGM_BaseConnectivityNode { get; set; }
        public virtual DbSet<DGM_BaseLine> DGM_BaseLine { get; set; }
        public virtual DbSet<DGM_BaseServicePoint> DGM_BaseServicePoint { get; set; }
        public virtual DbSet<DGM_BaseSubstation> DGM_BaseSubstation { get; set; }
        public virtual DbSet<DGM_BaseSwitch> DGM_BaseSwitch { get; set; }
        //public virtual DbSet<DGM_BaseSwitchedCapacitor> DGM_BaseSwitchedCapacitor { get; set; }
        public virtual DbSet<DGM_BaseTransformer> DGM_BaseTransformer { get; set; }
        //public virtual DbSet<DGM_Branch> DGM_Branch { get; set; }
        //public virtual DbSet<DGM_FeederHead> DGM_FeederHead { get; set; }
        public virtual DbSet<DGM_LineElectricalParameter> DGM_LineElectricalParameter { get; set; }
        //public virtual DbSet<DGM_ModelCase> DGM_ModelCase { get; set; }
        //public virtual DbSet<DGM_Node> DGM_Node { get; set; }
        //public virtual DbSet<DGM_NodeBranch> DGM_NodeBranch { get; set; }
        //public virtual DbSet<DGM_Switch> DGM_Switch { get; set; }
        //public virtual DbSet<DGM_TraceBranch> DGM_TraceBranch { get; set; }
        //public virtual DbSet<DGM_TraceFeederHead> DGM_TraceFeederHead { get; set; }
        //public virtual DbSet<DGM_TraceFeederHeadBusbar> DGM_TraceFeederHeadBusbar { get; set; }
        //public virtual DbSet<DGM_TraceNode> DGM_TraceNode { get; set; }
        //public virtual DbSet<DGM_Transformer> DGM_Transformer { get; set; }
        //public virtual DbSet<WS_GEO_DataPoint> WS_GEO_DataPoint { get; set; }
        //public virtual DbSet<CIM_EquivalentInjection> CIM_EquivalentInjection { get; set; }
        public virtual DbSet<DGM_BaseBusbarSection> DGM_BaseBusbarSection { get; set; }
        public virtual DbSet<DGM_BaseTerminalToConnectivityNode> DGM_BaseTerminalToConnectivityNode { get; set; }

        public virtual int PR_CIM_FileImport(string txt_path, string coor_path)
        {
            var txt_pathParameter = txt_path != null ?
                new ObjectParameter("txt_path", txt_path) :
                new ObjectParameter("txt_path", typeof(string));

            var coor_pathParameter = coor_path != null ?
                new ObjectParameter("coor_path", coor_path) :
                new ObjectParameter("coor_path", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_CIM_FileImport", txt_pathParameter, coor_pathParameter);
        }

        public virtual int PR_CIM_SetParentName() => ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_CIM_SetParentName");

        public virtual int PR_CIM_ToGISImport() => ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_CIM_ToGISImport");

        public virtual int PR_CIM_UpdatePositionPoint() => ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_CIM_UpdatePositionPoint");

        public virtual int PR_CIM_WebGeo_Import() => ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_CIM_WebGeo_Import");

        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    base.OnModelCreating(modelBuilder);
        //    modelBuilder.Entity<CIM_Model>().Property(a => a.ID).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
        //}
    }
}
