//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMImport
{
    using System;

    public partial class WS_GEO_DataPoint
    {
        public int Id { get; set; }
        public int MarkerId { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public int ParentId { get; set; }
        public int StatusId { get; set; }
        public byte Level { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string NavigationLink { get; set; }
        public string Value { get; set; }
        public Nullable<int> PhaseId { get; set; }
        public Nullable<System.DateTime> StatusDT { get; set; }
        public Nullable<int> AssetID { get; set; }
        public Nullable<int> LineMarkerId { get; set; }
        public string ActivePower { get; set; }
        public Nullable<int> SubstationId { get; set; }
    }
}
